connection: 
  host: irc.freenode.net
  port: 6697
  secure: true
  status_command: ACC
  debug: false
login: 
  nickname: TipBot
  username: TipBot
  realname: node.js rpc tipping bot
  nickserv_password: yourpass
channels: 
  - '#BotChannel'
log:
  file: bot.log
rpc:
  host: localhost
  port: rpc-port
  user: rpc-username
  pass: rpc-password
coin:
  withdrawal_fee: 2 
  min_withdraw: 10
  min_confirmations: 3
  min_tip: 1
  short_name: coin-shortname
  full_name: coin-name
webadmin:
  enabled: false
  port: 8080
  users:
    admin: your-pasword
urlget:
  enabled: true
  channels:
    - '#BotChannel'
joke:
  enabled: true
  url: http://api.icndb.com/jokes/random
random:
  enabled: true
  url: http://www.iheartquotes.com/api/v1/random?format=json&max_lines=1
allcoin:
  enabled: true
  coin: DOPE
  url: https://www.allcoin.com/api2/pair/DOPE_BTC
allcoin2:
  url: https://www.allcoin.com/api2/pair/
btc:
  enabled: true
  coin: BTC
  url: https://btc-e.com/api/3/ticker/btc_usd
cryptsy:
  enabled: true
  coin: FST
  url: http://pubapi.cryptsy.com/api.php?method=singlemarketdata&marketid=44
bittrex:
  enabled: true
  coin: DOPE
  url: https://bittrex.com/api/v1.1/public/getmarketsummary?market=btc-dope
bittrex2:
  url: https://bittrex.com/api/v1.1/public/getmarketsummary?market=
git:
  enabled: true
  host: '0.0.0.0'
  port: 3420
  channels:
    - '#BotGitChannel'
commands:
  commands:
    pm: true
    channel: false
  help:
    pm: false
    channel: true
  tip:
    pm: false
    channel: true 
  joke:
    pm: false
    channel: true
  random:
    pm: false
    channel: true
  ticker:
    pm: false
    channel: true
  cryptsy:
    pm: false
    channel: true
  bittrex:
    pm: false
    channel: true
  btc:
    pm: false
    channel: true
  rain: 
    pm: false
    channel: true      
  balance:
    pm: false
    channel: true
  withdraw:
    pm: false
    channel: true
  address:
    pm: false
    channel: true
  terms:
    pm: false
    channel: true
  block:
    pm: false
    channel: true
  diff:
    pm: false
    channel: true
  networkhps:
    pm: false
    channel: true
  info:
    pm: false
    channel: true
  bot:
    pm: false
    channel: true
messages:
  ticker: '%name% The current %coin% price at AllCoin. %coin%/BTC: %trade_price% - Volume: BTC: %exchange_volume% - %coin%: %type_volume%'
  tickererr: '%name% There was an error in the request either the AIP is down or %coin% dose not exist on AllCoin'
  cryptsy: '%name% The current %coin% price at Cryptsy. %coin%/BTC: %price% - Volume: %volume%'
  bittrex: '%name% The current %coin% price at BitTrex. %coin%/BTC: %last% - Volume: BTC: %basevolume% - %coin%: %volume%'
  bittrexerr: '%name% There was an error in the request either the AIP is down or %coin% dose not exist on BitTrex'
  btc: '%name% The current %coin% price at BTC-e. BTC: $%price_dollar% - Volume: %volume% BTC'
  joke: '%name% - %joke%'
  random: '%name% - %random%'
  error: 'Sorry %name%, something went wrong.'
  no_funds: 'Sorry %name%, you dont have enough funds (you are %short% %short_name% short)'
  not_identified: '%name%: You need to be identified with NickServ to use this command.'
  tipped: '%from% tipped %to% %amount% %short_name%! "/msg %nick% commands" to claim.'
  balance: '%name% has %balance% %short_name%.'
  balance_unconfirmed: '%name% has %balance% %short_name% (unconfirmed: %unconfirmed% %short_name%)'
  deposit_address: '%name%, your deposit address is %address%'
  withdraw_too_small: 'Sorry %name%, you need to withdraw at least %min_withdraw% %short_name% (you have %balance% %short_name%)'
  invalid_address: 'Sorry %name%, the address you specified is invalid (%address%).'
  tip_too_small: 'Sorry %from%, your tip to %to% (%amount% %short_name%) is too small (min. %min_tip% %short_name%).'
  rain_too_small: 'Sorry %from%, your rain (%amount% %short_name%) is too small (min. %min_rain% %short_name%). Increase the value or decrease max wet users.' 
  tip_self: "Sorry %name%, you can't tip yourself!"
  invalid_amount: 'Sorry %name%, "%amount%" is not a correct amount.'
  rain: '%name% rained %amount% %short_name% upon %list%.' 
  getdiff: 'Current Difficulty: %diff%'
  networkhps: 'Current Networkhps: %networkhps% KH/s'
  networmhps: 'Current Networkhps: %networkhps% MH/s'
  networghps: 'Current Networkhps: %networkhps% GH/s'
  networthps: 'Current Networkhps: %networkhps% TH/s'
  getblock: 'Current Block: %block%'
  infok: 'Current Networkhps: %networkhps% KH/s - Current Difficulty: %diff% - Current Block: %block%'
  infom: 'Current Networkhps: %networkhps% MH/s - Current Difficulty: %diff% - Current Block: %block%'
  infog: 'Current Networkhps: %networkhps% GH/s - Current Difficulty: %diff% - Current Block: %block%'
  infot: 'Current Networkhps: %networkhps% TH/s - Current Difficulty: %diff% - Current Block: %block%'
  gitpush:
    - '%name% Pushed a new commit to %repo% %message%'
    - '%url%'
  gitissue:
    - '%name% %action% an issue (%title%) on %repo%'
    - '%url%'
  gitissue_comment:
    - '%name% added a comment to (%title%) %url%'
  gitpull_request:
    - '%name% %action% pull request #%number% %headref%>%baseref% %title% %url%'
  bot:
    - '%nick% is a Node.js TipBot made by nrpatten and available at https://github.com/nrpatten/node-tip-bot'
  withdraw_success: 
    - '%name%: %amount% %short_name% has been withdrawn from your account to %address%'
    - 'You have been charged %withdrawal_fee% %short_name% withdrawal fee.'
    - 'Transaction %transaction% completed.'
  help:
    - 'Plaese type /msg %nick% commands'
  commands:
    - '!balance - displays your current wallet balance'
    - '!address - displays %full_name% address where you can send your funds to the tip bot'
    - '!withdraw <%full_name% address> - withdraws your whole wallet balance to specified address (you will be charged %withdrawal_fee% %short_name% withdrawal fee)'
    - '!tip <nick> <amount> - sends the specified amount of %full_name% to the specified nickname'
    - '!rain <amount> [max] - splits amount coins between max users or the whole channel'
    - '!diff - displays the current network difficulty'
    - '!networkhps - displays the current network hashpersec'
    - '!block - displays the current network block'
    - '!info - displays the current network hashpersec, difficulty, block'
    - '!ticker - displays the current AllCoin Coin Price/Volume, You can also use it to search for a coin, eg. !ticker CZC'
    - '!cryptsy - displays the current Cryptsy Coin Price/Volume'
    - '!bittrex - displays the current BitTrex Coin Price/Volume, You can also use it to search for a coin, eg. !ticker CANN'
    - '!btc - displays the current BTC-e BitCoin Price/Volume'
    - '!joke - displays a joke'
    - '!random - displays a random quote'
    - '!bot - displays info about the bot and where to download the source code.'
    - '!terms - displays terms and conditions for using %nick%'
  terms:
    - 'There are no fees to use %nick%, with the exception of %withdrawal_fee% %short_name% fee on withdrawals.'
    - 'Warning: This service is provided "as is" without warranty of any kind, either express or implied, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, non-infringement, error-free or uninterrupted service. You are using this service at your own risk; in addition, the coins in your account are only as secure as your IRC account is. Do not hold large sums of coins here; simply withdraw or tip others.'
